version: "3.9"

services:
  db:
    image: wootestacr.azurecr.io/mysql
    container_name: azure-woo-db
    #volumes:
    #  - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    container_name: azure-woo-wp
    image: wootestacr.azurecr.io/wootest
    #volumes:
    #  - wordpress_data:/var/www/html
    #  - ./:/var/www/html/wp-content/plugins/nofrixion-for-woocommerce
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

#volumes:
#  db_data: {}
#  wordpress_data: {}
