version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: azure-woo-db
    volumes:
      - volmysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    container_name: azure-woo-wp
    image: wordpress
    domainname: "woowp"
    volumes:
      - volwp:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  volmysql:
    driver: azure_file
    driver_opts:
      share_name: wootestmysql
      storage_account_name: wooteststorage
  volwp:
    driver: azure_file
    driver_opts:
      share_name: wootestwp
      storage_account_name: wooteststorage
