#name: Build and deploy to WordPress.org
on:
  push:
  #release:
  #  types: [published]
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Composer install not needed as long as we have the vendor/ directory committed.
      #- name: Install Composer dependencies
      #  uses: php-actions/composer@v6
      #  with:
      #    dev: no
      #    php_version: 7.4
      #    php_extensions: bcmath
      #- name: Build assets and translation files
      #  run: |
      #    npm install
      #    npm run build
      - name: Create release artifact.
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'nofrixion-for-woocommerce.zip'
          exclusions: '*.git* /*node_modules/* /*bin/* *.github* *.wordpress-org* /*tests/* Dockerfile docker-compose* *.lock package-lock.json phpunit.xml.dist'
      - name: Upload artifact to release page.
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'nofrixion-for-woocommerce.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: WordPress Plugin Deploy
      #  id: deploy
      #  uses: 10up/action-wordpress-plugin-deploy@stable
      #  with:
      #    generate-zip: true
      #  env:
      #    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      #    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      #    SLUG: nofrixion-for-woocommerce
      # This only works if the above Wordpress deploy step created the asset.
      #- name: Upload release asset
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ github.event.release.upload_url }}
      #    asset_path: ${{ steps.deploy.outputs.zip-path }}
      #    asset_name: nofrixion-for-woocommerce.zip
      #    asset_content_type: application/zip
